# docker-compose.yml
version: "3.10"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "sqlite:///./device_data.db" # Указываем DATABASE_URL для контейнера
